const sentences = [
// ===== 1-20: 写代码 & 提PR =====
{zh:"我刚提了一个PR，你有空的时候帮我看一下。", en:"I've just opened a PR — take a look when you get a chance.", vocab:"PR, opened"},
{zh:"这个PR修复了登录页面偶发的崩溃问题。", en:"This PR fixes an intermittent crash on the login page.", vocab:"intermittent, crash"},
{zh:"我在提交信息里写清楚了改动的原因。", en:"I've explained the reasoning behind the changes in the commit message.", vocab:"reasoning, commit message"},
{zh:"这个改动比较大，我拆成了三个小PR方便审查。", en:"It's a fairly large change — I've split it into three smaller PRs to make review easier.", vocab:"split, review"},
{zh:"这个PR依赖上一个，合并顺序要注意一下。", en:"This PR depends on the previous one — make sure to merge them in order.", vocab:"depends on, merge"},
{zh:"我在PR描述里加了截图，方便理解改动效果。", en:"I've added screenshots to the PR description so you can see what changed.", vocab:"screenshots, description"},
{zh:"这只是一个草稿PR，还没准备好合并，先给你看个方向。", en:"This is just a draft PR — not ready to merge yet, just wanted to share the direction.", vocab:"draft, direction"},
{zh:"我本地测试过了，功能正常。", en:"I've tested this locally and everything looks good.", vocab:"locally, tested"},
{zh:"这个分支已经落后主干很多了，我先rebase一下。", en:"This branch is pretty far behind main — I'll rebase it first.", vocab:"rebase, behind"},
{zh:"我给这个函数加了单元测试。", en:"I've added unit tests for this function.", vocab:"unit tests"},
{zh:"这个PR主要是重构，没有改任何功能逻辑。", en:"This PR is purely a refactor — no functional changes.", vocab:"refactor, functional"},
{zh:"我把几个重复的逻辑抽取成了公共方法。", en:"I've extracted some duplicated logic into a shared helper function.", vocab:"extracted, duplicated, helper"},
{zh:"这个改动涉及数据库schema，需要跑一下migration。", en:"This change affects the database schema — you'll need to run the migration.", vocab:"schema, migration"},
{zh:"我更新了README，把新的环境变量配置说明加进去了。", en:"I've updated the README to document the new environment variables.", vocab:"environment variables, document"},
{zh:"这个PR关联了Jira里的那张ticket。", en:"This PR is linked to the Jira ticket.", vocab:"linked, ticket"},
{zh:"我在代码里留了TODO，后续再处理边界情况。", en:"I've left a TODO in the code — I'll handle the edge cases in a follow-up.", vocab:"TODO, edge cases, follow-up"},
{zh:"请求你的review，大概改了200行代码。", en:"Requesting your review — it's about 200 lines changed overall.", vocab:"requesting, review"},
{zh:"这个改动修复的是生产环境的bug，比较紧急。", en:"This fixes a bug in production — it's fairly urgent.", vocab:"production, urgent"},
{zh:"我把硬编码的配置移到了环境变量里。", en:"I've moved the hardcoded config values into environment variables.", vocab:"hardcoded, config"},
{zh:"CI跑绿了，可以合并了。", en:"CI is green — it's ready to merge.", vocab:"CI, green"},

// ===== 21-40: Code Review — 给反馈 =====
{zh:"整体看起来不错，有几个小地方想讨论一下。", en:"Looks good overall — just a few small things I'd like to discuss.", vocab:"overall, discuss"},
{zh:"这个变量名不太清楚，能改得更有描述性吗？", en:"This variable name isn't very clear — could you make it more descriptive?", vocab:"descriptive, variable"},
{zh:"这里有个潜在的空指针问题，建议加一下判断。", en:"There's a potential null pointer issue here — I'd suggest adding a check.", vocab:"null pointer, potential"},
{zh:"这段逻辑挺复杂的，能加几行注释解释一下吗？", en:"This logic is a bit complex — could you add a few comments to explain what's going on?", vocab:"complex, comments"},
{zh:"非阻塞性建议：这里可以用map代替for循环，更简洁。", en:"Non-blocking: you could use map here instead of a for loop — it's a bit cleaner.", vocab:"non-blocking, map"},
{zh:"这个函数太长了，考虑拆分一下？", en:"This function is getting a bit long — worth splitting it up?", vocab:"splitting, function"},
{zh:"这里的错误处理感觉不够，如果请求失败了会怎样？", en:"The error handling here feels a bit thin — what happens if the request fails?", vocab:"error handling, request"},
{zh:"这个改动会破坏已有的API接口吗？", en:"Will this change break any existing API contracts?", vocab:"break, API contracts"},
{zh:"我觉得这个逻辑可以移到服务层，让controller更干净。", en:"I think this logic could live in the service layer — it'd keep the controller cleaner.", vocab:"service layer, controller"},
{zh:"这里直接拼接SQL有注入风险，建议用参数化查询。", en:"Concatenating SQL directly here is a risk — I'd recommend using parameterised queries.", vocab:"SQL injection, parameterised"},
{zh:"测试覆盖了happy path，但有没有测试异常情况？", en:"The tests cover the happy path, but have you tested the failure cases too?", vocab:"happy path, failure cases"},
{zh:"这个接口的返回格式跟其他接口不太一致，能统一一下吗？", en:"The response format here is a bit inconsistent with the rest of the API — could you align it?", vocab:"inconsistent, align"},
{zh:"这里有重复代码，可以复用已有的工具函数。", en:"There's some duplication here — you could reuse the existing utility function.", vocab:"duplication, utility function"},
{zh:"这个变更需要更新API文档吗？", en:"Does this change need an update to the API docs?", vocab:"API docs, update"},
{zh:"我不太确定这个逻辑是否正确，能解释一下你的思路吗？", en:"I'm not sure about this logic — could you walk me through your thinking?", vocab:"walk through, thinking"},
{zh:"这里的命名跟项目规范不一致，参考一下我们的style guide。", en:"The naming here doesn't quite match our conventions — have a look at the style guide.", vocab:"conventions, style guide"},
{zh:"这个条件判断有点绕，能简化一下吗？", en:"This condition is a bit convoluted — is there a simpler way to write it?", vocab:"convoluted, condition"},
{zh:"建议把这个魔法数字定义成一个有意义的常量。", en:"I'd suggest extracting this magic number into a named constant.", vocab:"magic number, constant"},
{zh:"这个改动感觉超出了这个PR的范围，可以单独开一个PR吗？", en:"This feels out of scope for this PR — could it go in a separate one?", vocab:"out of scope, separate"},
{zh:"LGTM，可以合并了。", en:"LGTM — good to merge.", vocab:"LGTM"},

// ===== 41-60: Code Review — 回应反馈 =====
{zh:"好建议，我已经按你说的改了。", en:"Good point — I've updated it accordingly.", vocab:"accordingly, updated"},
{zh:"这里我是故意这么写的，因为这个接口有一个特殊行为。", en:"This was intentional — the API has a quirk that requires this approach.", vocab:"intentional, quirk"},
{zh:"我理解你的顾虑，但考虑到性能问题，我倾向于保持现在的写法。", en:"I hear you, but given the performance implications, I'd prefer to keep it as is.", vocab:"performance, implications"},
{zh:"你说得对，我修了。", en:"You're right — fixed.", vocab:"fixed"},
{zh:"我在新的commit里解决了你提的所有问题。", en:"I've addressed all your comments in the latest commit.", vocab:"addressed, latest commit"},
{zh:"这个TODO是留给下个迭代的，这个PR先不处理。", en:"That TODO is intentionally left for the next sprint — out of scope for this PR.", vocab:"sprint, intentionally"},
{zh:"我对这里不太确定，你有什么推荐的方案吗？", en:"I'm not sure about the best approach here — do you have a recommendation?", vocab:"recommendation, approach"},
{zh:"感谢你的详细review，学到了不少。", en:"Thanks for the thorough review — I learned a lot from your comments.", vocab:"thorough, review"},
{zh:"我加了你建议的测试用例。", en:"I've added the test cases you suggested.", vocab:"test cases, suggested"},
{zh:"我重构了那个函数，现在应该更好读了。", en:"I've refactored that function — it should be a lot easier to follow now.", vocab:"refactored, easier to follow"},
{zh:"我觉得这两种方案各有利弊，我们可以开个小会讨论一下吗？", en:"I think there are trade-offs either way — could we have a quick chat to discuss?", vocab:"trade-offs, discuss"},
{zh:"我把那个魔法数字提取成常量了。", en:"I've extracted that magic number into a constant — good catch.", vocab:"extracted, good catch"},
{zh:"非常抱歉，我误解了你的意思，现在重新改了。", en:"Sorry, I misread your comment — I've reworked it now.", vocab:"misread, reworked"},
{zh:"我把这个改动移到了一个单独的commit里，方便你看改动历史。", en:"I've moved this into a separate commit to keep the history clean.", vocab:"commit, history"},
{zh:"我在代码里加了注释解释为什么这么做。", en:"I've added a comment explaining the reasoning.", vocab:"reasoning, comment"},
{zh:"你提的那个边界情况我测试了，没有问题。", en:"I've tested the edge case you mentioned — it handles it fine.", vocab:"edge case, handles"},
{zh:"这个类型报错是老代码留下来的，这个PR里一起修了。", en:"That type error was pre-existing — I've fixed it here while I was at it.", vocab:"pre-existing, type error"},
{zh:"我把那个大函数拆成了三个小函数，现在应该好多了。", en:"I've broken that large function into three smaller ones — much easier to read now.", vocab:"broken down, readable"},
{zh:"你说的性能问题我写了一个benchmark来验证。", en:"I've written a benchmark to validate the performance concern you raised.", vocab:"benchmark, validate"},
{zh:"这个PR已经根据你的反馈更新了，请再看一遍。", en:"I've updated the PR based on your feedback — ready for another look.", vocab:"updated, feedback"},

// ===== 61-80: Git & 分支操作 =====
{zh:"我需要把main的最新代码同步到我的分支。", en:"I need to pull in the latest changes from main.", vocab:"pull in, latest"},
{zh:"合并的时候有冲突，我来处理一下。", en:"There are merge conflicts — I'll sort them out.", vocab:"merge conflicts, sort out"},
{zh:"我不小心提交到了错误的分支。", en:"I accidentally committed to the wrong branch.", vocab:"accidentally, committed"},
{zh:"这个commit信息写错了，我需要amend一下。", en:"The commit message is wrong — I need to amend it.", vocab:"amend, commit message"},
{zh:"能帮我review一下这个rebase之后的改动吗？", en:"Could you take another look after I've rebased?", vocab:"rebased, review"},
{zh:"我把这个功能分支从develop切出来的。", en:"I branched off develop for this feature.", vocab:"branched off, feature"},
{zh:"这个commit需要cherry-pick到hotfix分支。", en:"This commit needs to be cherry-picked into the hotfix branch.", vocab:"cherry-pick, hotfix"},
{zh:"我把上次的提交revert了，因为引入了一个新bug。", en:"I've reverted the last commit — it introduced a new bug.", vocab:"reverted, introduced"},
{zh:"我用了git stash把当前改动暂存起来，先切去处理紧急的bug。", en:"I've stashed my current changes and switched over to fix the urgent bug.", vocab:"stashed, switched"},
{zh:"这个PR已经有很多commit了，合并前要不要squash一下？", en:"There are quite a few commits here — should we squash them before merging?", vocab:"squash, commits"},
{zh:"我们应该用merge还是rebase？", en:"Should we merge or rebase?", vocab:"merge, rebase"},
{zh:"我不小心把密钥提交进去了，需要立刻从历史记录里删除。", en:"I accidentally committed a secret — we need to remove it from the history immediately.", vocab:"secret, history"},
{zh:"这个分支命名规范是什么？", en:"What's our branch naming convention?", vocab:"naming convention, branch"},
{zh:"我在本地把这个bug重现了，正在找是哪个commit引入的。", en:"I've reproduced the bug locally — trying to track down which commit introduced it.", vocab:"reproduced, track down"},
{zh:"请不要直接往main分支推代码。", en:"Please don't push directly to main.", vocab:"push, main"},
{zh:"这个分支可以删掉了，已经合并了。", en:"This branch can be deleted — it's already been merged.", vocab:"deleted, merged"},
{zh:"我在git log里看看谁改了这行代码。", en:"I'll check the git log to see who last changed this line.", vocab:"git log, blame"},
{zh:"我们要给这个版本打一个tag。", en:"We need to tag this release.", vocab:"tag, release"},
{zh:"我rebase的时候搞乱了，想从头再来。", en:"I've made a mess of the rebase — I want to start over.", vocab:"start over, rebase"},
{zh:"你的分支跟main有冲突，在我合并之前你先解决一下。", en:"Your branch has conflicts with main — please resolve them before I merge.", vocab:"conflicts, resolve"},

// ===== 81-100: 技术讨论 & 设计决策 =====
{zh:"我们来讨论一下这个功能的技术方案。", en:"Let's talk through the technical approach for this feature.", vocab:"technical approach, feature"},
{zh:"这两种方案各有什么利弊？", en:"What are the trade-offs between these two approaches?", vocab:"trade-offs, approaches"},
{zh:"我倾向于方案B，因为更容易扩展。", en:"I'd lean towards option B — it's easier to scale.", vocab:"lean towards, scale"},
{zh:"这个改动对性能有什么影响？", en:"What's the performance impact of this change?", vocab:"performance impact"},
{zh:"我们先做一个最简版本，后续再迭代。", en:"Let's start with a minimal version and iterate from there.", vocab:"minimal, iterate"},
{zh:"这个需求有点模糊，我们需要先跟产品对齐。", en:"The requirements are a bit vague — we need to align with the product team first.", vocab:"vague, align"},
{zh:"引入这个新依赖合理吗？", en:"Is it worth adding this new dependency?", vocab:"dependency, worth"},
{zh:"我们需要考虑这个方案的安全隐患。", en:"We need to think about the security implications of this approach.", vocab:"security, implications"},
{zh:"这里有个技术债，我们需要在下个迭代里还掉。", en:"There's some technical debt here — we should address it next sprint.", vocab:"technical debt, address"},
{zh:"我先做一个概念验证，确认这个方案可行。", en:"I'll put together a proof of concept first to validate the approach.", vocab:"proof of concept, validate"},
{zh:"我们用缓存来解决这个性能瓶颈吧。", en:"Let's use caching to fix this performance bottleneck.", vocab:"caching, bottleneck"},
{zh:"这里我们应该做异步处理还是同步处理？", en:"Should this be handled asynchronously or synchronously?", vocab:"asynchronously, synchronously"},
{zh:"这个接口设计我有点顾虑，这样改以后会不好向后兼容。", en:"I have some concerns about this API design — it'll be hard to keep it backwards compatible.", vocab:"backwards compatible, API design"},
{zh:"我们应该在哪一层处理这个业务逻辑？", en:"Which layer should own this business logic?", vocab:"business logic, layer"},
{zh:"这个功能需要做降级方案，防止第三方接口挂掉。", en:"We need a fallback in case the third-party service goes down.", vocab:"fallback, third-party"},
{zh:"单体应用现在已经很难维护了，我们讨论一下是否要拆成微服务。", en:"The monolith is getting hard to maintain — worth discussing whether to break it into microservices.", vocab:"monolith, microservices"},
{zh:"我们先不过度设计，等需求真正来了再扩展。", en:"Let's not over-engineer this — we can extend it when we actually need to.", vocab:"over-engineer, extend"},
{zh:"这个功能上线后我们需要加监控和报警。", en:"Once this ships, we'll need to add monitoring and alerts.", vocab:"monitoring, alerts"},
{zh:"我来写技术方案文档，大家review之后再开始开发。", en:"I'll write up the technical design doc — let's get everyone's input before we start building.", vocab:"design doc, input"},
{zh:"我们做个简短的技术分享，把这块的背景给团队讲清楚。", en:"Let's do a quick tech talk to bring the team up to speed on the background.", vocab:"tech talk, up to speed"},

// ===== 101-120: 讲代码结构 & 导览 =====
{zh:"我来带大家过一遍这块代码的整体结构。", en:"Let me walk you through the overall structure of this code.", vocab:"walk through, structure"},
{zh:"这个类负责处理所有跟用户认证相关的逻辑。", en:"This class is responsible for handling all the authentication logic.", vocab:"responsible for, authentication"},
{zh:"这里我们定义了一个接口，下面这个是它的具体实现。", en:"Here we define the interface, and this is the concrete implementation.", vocab:"interface, concrete implementation"},
{zh:"这个方法接收一个用户ID，返回对应的用户对象。", en:"This method takes a user ID and returns the corresponding user object.", vocab:"takes, returns, corresponding"},
{zh:"这个类继承自BaseService，复用了里面的公共方法。", en:"This class extends BaseService and reuses the common methods defined there.", vocab:"extends, reuses"},
{zh:"这里用的是单例模式，整个应用只会有一个实例。", en:"This is a singleton — there'll only ever be one instance of this across the whole app.", vocab:"singleton, instance"},
{zh:"这块用了工厂模式，根据类型动态创建不同的对象。", en:"We're using a factory pattern here to dynamically create different objects based on the type.", vocab:"factory pattern, dynamically"},
{zh:"这个注解的作用是让Spring自动注入这个依赖。", en:"This annotation tells Spring to automatically inject this dependency.", vocab:"annotation, inject, dependency"},
{zh:"这是一个泛型方法，T可以是任意类型。", en:"This is a generic method — T can be any type.", vocab:"generic, type parameter"},
{zh:"这个包里放的都是DTO，专门用来传输数据的。", en:"This package contains all our DTOs — they're purely for data transfer.", vocab:"DTO, data transfer"},
{zh:"这两个类之间是一对多的关系。", en:"There's a one-to-many relationship between these two classes.", vocab:"one-to-many, relationship"},
{zh:"这一层是service层，专门放业务逻辑。", en:"This is the service layer — it's where all the business logic lives.", vocab:"service layer, business logic"},
{zh:"controller只负责接收请求和返回响应，不放业务逻辑。", en:"The controller just handles incoming requests and sends back responses — no business logic here.", vocab:"controller, request, response"},
{zh:"这个接口实现了Serializable，是为了支持对象序列化。", en:"This class implements Serializable to support object serialisation.", vocab:"Serializable, serialisation"},
{zh:"这里我们用了建造者模式，避免构造函数参数太多。", en:"We're using the builder pattern here to avoid a constructor with too many parameters.", vocab:"builder pattern, constructor"},
{zh:"这个枚举定义了所有可能的订单状态。", en:"This enum defines all the possible order states.", vocab:"enum, states"},
{zh:"这个抽象类提供了一些默认实现，子类可以选择性覆盖。", en:"This abstract class provides some default implementations — subclasses can override them as needed.", vocab:"abstract class, override, subclass"},
{zh:"这里用了@Override注解，表明这个方法是覆盖父类的。", en:"The @Override annotation here tells us this method is overriding the parent class.", vocab:"@Override, parent class"},
{zh:"这些是私有字段，只能在类内部访问。", en:"These are private fields — they can only be accessed within the class.", vocab:"private, fields, access"},
{zh:"这个静态方法不依赖任何实例，可以直接通过类名调用。", en:"This is a static method — it doesn't depend on an instance, so you call it directly on the class.", vocab:"static, instance"},

// ===== 121-140: 讲数据类型 & 变量 =====
{zh:"这里我们做了一个强制类型转换，把Object转成String。", en:"Here we're doing an explicit cast — converting the Object to a String.", vocab:"cast, explicit, convert"},
{zh:"这个变量可能为null，所以我们先做了一个非空判断。", en:"This variable could be null, so we check for that first.", vocab:"null check, variable"},
{zh:"Java里的int是基本类型，Integer是它的包装类。", en:"In Java, int is a primitive type and Integer is its wrapper class.", vocab:"primitive, wrapper class"},
{zh:"这里用了Optional来避免直接返回null。", en:"We're using Optional here to avoid returning null directly.", vocab:"Optional, null"},
{zh:"这个List用了泛型，只能存放String类型的元素。", en:"This List is typed — it can only hold Strings.", vocab:"generics, typed, List"},
{zh:"这是一个不可变对象，创建之后就不能再修改了。", en:"This is an immutable object — once it's created, it can't be changed.", vocab:"immutable, modified"},
{zh:"这里用的是Map，通过key可以快速查找对应的value。", en:"We're using a Map here — it lets us look up values by key in constant time.", vocab:"Map, key-value, constant time"},
{zh:"这个字段加了final，表示它只能被赋值一次。", en:"This field is marked final — it can only be assigned once.", vocab:"final, assigned"},
{zh:"这里做了自动装箱，int被自动转换成了Integer。", en:"There's autoboxing happening here — the int is automatically converted to an Integer.", vocab:"autoboxing, converted"},
{zh:"这个方法返回的是一个新的List副本，不会影响原来的数据。", en:"This method returns a copy of the list — it won't affect the original.", vocab:"copy, original, return"},
{zh:"这里用了var做类型推断，让代码更简洁。", en:"We're using var here for type inference — it keeps the code cleaner.", vocab:"var, type inference"},
{zh:"这个数组长度是固定的，如果需要动态增长要用ArrayList。", en:"Arrays have a fixed size in Java — use an ArrayList if you need something that grows.", vocab:"fixed size, ArrayList, dynamic"},
{zh:"这个String是不可变的，每次拼接都会创建新对象。", en:"Strings are immutable in Java — each concatenation creates a new object.", vocab:"immutable, concatenation"},
{zh:"这里用了StringBuilder来做字符串拼接，性能更好。", en:"We're using StringBuilder for string concatenation here — it's much more efficient.", vocab:"StringBuilder, concatenation, efficient"},
{zh:"这个Map的key是枚举类型，查找速度非常快。", en:"The map's keys are enums here — lookups are very fast.", vocab:"enum, key, lookup"},
{zh:"这个对象实现了equals和hashCode，确保可以正确比较。", en:"This class overrides equals and hashCode so objects can be compared correctly.", vocab:"equals, hashCode, override"},
{zh:"这里用了Collections.unmodifiableList，防止外部代码修改这个列表。", en:"We're wrapping it in an unmodifiable list to prevent external code from changing it.", vocab:"unmodifiable, prevent"},
{zh:"这个lambda表达式等价于实现了Comparator接口。", en:"This lambda is essentially implementing the Comparator interface.", vocab:"lambda, Comparator, interface"},
{zh:"这里用了Stream API来过滤和转换集合。", en:"We're using the Stream API here to filter and transform the collection.", vocab:"Stream API, filter, transform"},
{zh:"注意这里比较的是对象引用而不是值，应该用equals。", en:"Watch out — this is comparing references, not values. You should use equals here.", vocab:"reference, equals, compare"},

// ===== 141-160: 讲控制流 & 异常处理 =====
{zh:"这里的提前return是为了减少嵌套，让代码更好读。", en:"This early return is here to reduce nesting and make the code easier to follow.", vocab:"early return, nesting"},
{zh:"这个while循环会一直跑，直到队列为空。", en:"This while loop keeps running until the queue is empty.", vocab:"while loop, queue"},
{zh:"这里用了三元运算符，代替了简单的if-else。", en:"We're using a ternary operator here instead of a simple if-else.", vocab:"ternary operator, if-else"},
{zh:"这个switch语句处理了所有可能的枚举值。", en:"This switch statement handles all the possible enum values.", vocab:"switch, enum"},
{zh:"这里catch了特定的异常类型，而不是直接catch所有Exception。", en:"We're catching a specific exception type here rather than catching everything.", vocab:"catch, specific, exception"},
{zh:"这个异常被捕获后重新包装成了业务异常再抛出。", en:"The exception is caught here, wrapped in a business exception, and rethrown.", vocab:"caught, wrapped, rethrown"},
{zh:"finally块里的代码无论是否出现异常都会执行。", en:"The code in the finally block always runs, whether or not an exception is thrown.", vocab:"finally, exception"},
{zh:"这里直接把异常吞掉了，这是个问题——至少要打一条日志。", en:"The exception is being swallowed here — that's a problem. We should at least log it.", vocab:"swallowed, log, exception"},
{zh:"这个自定义异常继承了RuntimeException，不需要强制捕获。", en:"This custom exception extends RuntimeException, so callers don't have to catch it.", vocab:"RuntimeException, custom exception, unchecked"},
{zh:"这里用了try-with-resources，确保资源自动关闭。", en:"We're using try-with-resources here to make sure the resource is closed automatically.", vocab:"try-with-resources, AutoCloseable"},
{zh:"这个for-each循环遍历了集合里的每一个元素。", en:"This for-each loop iterates over every element in the collection.", vocab:"for-each, iterate, collection"},
{zh:"这里用break跳出了循环，不需要遍历剩下的元素了。", en:"We break out of the loop here — no need to keep iterating.", vocab:"break, loop, iterate"},
{zh:"这个递归调用需要注意栈溢出的风险。", en:"Watch out for stack overflow with this recursive call.", vocab:"recursive, stack overflow"},
{zh:"这里的条件判断顺序很重要，短路求值可以避免空指针。", en:"The order of conditions matters here — short-circuit evaluation prevents a NullPointerException.", vocab:"short-circuit, NullPointerException, evaluation"},
{zh:"这个方法声明了checked exception，调用方必须处理。", en:"This method declares a checked exception, so callers are forced to handle it.", vocab:"checked exception, declare"},
{zh:"这个Assert是用于开发阶段的，生产环境不要依赖它。", en:"This assert is just for development — don't rely on it in production.", vocab:"assert, production"},
{zh:"这里用了Optional的orElseThrow，如果为空直接抛出异常。", en:"We're using orElseThrow here — if the value is empty, it throws an exception immediately.", vocab:"orElseThrow, Optional"},
{zh:"这个if条件太长了，我把它拆成了几个有名字的变量。", en:"The condition was getting too long, so I've extracted it into named variables.", vocab:"extracted, named variables, condition"},
{zh:"这里用了多态，运行时会根据实际类型调用对应的方法。", en:"We're relying on polymorphism here — the right method gets called at runtime based on the actual type.", vocab:"polymorphism, runtime, dispatch"},
{zh:"这个方法不应该抛出受检异常，改成非受检的更合适。", en:"This method shouldn't throw a checked exception — an unchecked one makes more sense here.", vocab:"checked, unchecked, exception"},

// ===== 161-180: 讲并发 & 线程安全 =====
{zh:"这个方法不是线程安全的，多线程同时调用会有问题。", en:"This method isn't thread-safe — calling it from multiple threads simultaneously will cause issues.", vocab:"thread-safe, concurrent"},
{zh:"这里加了synchronized，同一时间只有一个线程能进来。", en:"We've added synchronized here so only one thread can enter at a time.", vocab:"synchronized, thread"},
{zh:"这个变量加了volatile，保证多线程下的可见性。", en:"This field is marked volatile to ensure visibility across threads.", vocab:"volatile, visibility"},
{zh:"这里可能有竞态条件，两个线程同时写会导致数据不一致。", en:"There's a potential race condition here — two threads writing at the same time could corrupt the data.", vocab:"race condition, corrupt"},
{zh:"这里用了AtomicInteger，保证自增操作的原子性。", en:"We're using AtomicInteger here to make the increment operation atomic.", vocab:"AtomicInteger, atomic, increment"},
{zh:"这个方法是一个阻塞调用，会一直等到有结果返回。", en:"This is a blocking call — it'll wait until it gets a result.", vocab:"blocking, wait"},
{zh:"这里用了CompletableFuture做异步处理，不阻塞主线程。", en:"We're using CompletableFuture here to handle this asynchronously without blocking the main thread.", vocab:"CompletableFuture, asynchronous, non-blocking"},
{zh:"这个线程池的大小要根据实际负载来调整。", en:"The thread pool size should be tuned based on the actual workload.", vocab:"thread pool, tuned, workload"},
{zh:"这里有死锁的风险——两个线程互相等待对方释放锁。", en:"There's a risk of deadlock here — both threads are waiting for each other to release the lock.", vocab:"deadlock, lock, release"},
{zh:"这个Map不是线程安全的，并发场景要用ConcurrentHashMap。", en:"HashMap isn't thread-safe — use ConcurrentHashMap in a concurrent context.", vocab:"ConcurrentHashMap, thread-safe"},
{zh:"这里用了读写锁，允许多个线程同时读，但写的时候独占。", en:"We're using a read-write lock here — multiple threads can read simultaneously, but writes are exclusive.", vocab:"read-write lock, exclusive"},
{zh:"这个@Async注解让这个方法在单独的线程里异步执行。", en:"The @Async annotation here makes this method run asynchronously in a separate thread.", vocab:"@Async, asynchronous"},
{zh:"这里用了ThreadLocal，每个线程都有自己独立的变量副本。", en:"We're using ThreadLocal here so each thread has its own copy of this variable.", vocab:"ThreadLocal, thread-local"},
{zh:"这个Future.get()会阻塞，直到异步任务完成。", en:"Future.get() blocks here until the async task finishes.", vocab:"Future, blocking, async"},
{zh:"这里用了CountDownLatch来等待多个子任务全部完成。", en:"We're using a CountDownLatch to wait for all the subtasks to finish.", vocab:"CountDownLatch, subtasks"},
{zh:"这个单例用了双重检查锁来保证线程安全的懒加载。", en:"This singleton uses double-checked locking for thread-safe lazy initialisation.", vocab:"double-checked locking, lazy initialisation, singleton"},
{zh:"这里要注意内存泄漏——ThreadLocal用完要记得remove。", en:"Watch out for memory leaks here — always remove the ThreadLocal value when you're done.", vocab:"memory leak, ThreadLocal, remove"},
{zh:"这个任务提交给了线程池，不会阻塞当前线程。", en:"This task is submitted to the thread pool — it won't block the current thread.", vocab:"thread pool, submitted, non-blocking"},
{zh:"这里用了Semaphore来限制同时访问这个资源的线程数量。", en:"We're using a Semaphore to limit how many threads can access this resource at the same time.", vocab:"Semaphore, limit, concurrent"},
{zh:"这个接口的实现要保证幂等性，重复调用不会有副作用。", en:"The implementation needs to be idempotent — calling it multiple times shouldn't have any side effects.", vocab:"idempotent, side effects"},

// ===== 181-200: 讲性能 & 设计原则 + 指出问题 =====
{zh:"这个循环是O(n²)的，数据量大的时候会很慢。", en:"This loop is O(n²) — it's going to be slow with large datasets.", vocab:"O(n²), complexity, performance"},
{zh:"这里每次都查一次数据库，加个缓存会好很多。", en:"This hits the database on every call — adding a cache here would help a lot.", vocab:"cache, database, performance"},
{zh:"这个方法违反了单一职责原则，做了太多不相关的事情。", en:"This method violates the single responsibility principle — it's doing too many unrelated things.", vocab:"single responsibility, SRP"},
{zh:"这里service层和DAO层耦合太紧了，不好测试。", en:"The service layer is too tightly coupled to the DAO — it makes testing difficult.", vocab:"tightly coupled, DAO, testability"},
{zh:"这个if-else链太长了，考虑用策略模式重构一下。", en:"This if-else chain is getting long — worth refactoring with a strategy pattern.", vocab:"strategy pattern, refactor"},
{zh:"这里加了懒加载，只有真正需要的时候才初始化。", en:"We've added lazy initialisation here — it only gets created when it's actually needed.", vocab:"lazy initialisation, performance"},
{zh:"这个类的职责太多了，我们应该把它拆开。", en:"This class has too many responsibilities — we should split it up.", vocab:"responsibilities, split"},
{zh:"这里用了索引，查询速度从O(n)优化到了O(log n)。", en:"We've added an index here — query time drops from O(n) to O(log n).", vocab:"index, O(log n), query"},
{zh:"这里有N+1查询的问题，应该用join一次性把数据取出来。", en:"There's an N+1 query problem here — we should use a join to fetch everything in one go.", vocab:"N+1 query, join"},
{zh:"这个方法依赖了一个全局变量，很难写单元测试。", en:"This method depends on a global variable — that makes it really hard to unit test.", vocab:"global variable, unit test, dependency"},
{zh:"这里违反了开闭原则，每次加新类型都要改这个方法。", en:"This violates the open-closed principle — every new type requires a change to this method.", vocab:"open-closed principle, OCP"},
{zh:"这段代码里有内存泄漏，对象一直被持有，没有被GC回收。", en:"There's a memory leak here — objects are being held onto and never garbage collected.", vocab:"memory leak, GC, garbage collection"},
{zh:"这个地方可能有NPE，调用前应该判断一下是否为null。", en:"There's a potential NPE here — we should null-check before calling this.", vocab:"NPE, NullPointerException, null-check"},
{zh:"这个接口设计暴露了太多内部实现细节，违反了封装原则。", en:"This interface exposes too many internal implementation details — it breaks encapsulation.", vocab:"encapsulation, interface, implementation"},
{zh:"这里的异常被吞掉了，排查问题的时候会很头疼。", en:"The exception is being swallowed here — it'll make debugging a nightmare.", vocab:"swallowed, debugging, exception"},
{zh:"这个方法的圈复杂度太高了，应该拆成几个小方法。", en:"The cyclomatic complexity of this method is too high — it should be broken into smaller ones.", vocab:"cyclomatic complexity, refactor"},
{zh:"这里用了反射，性能会比直接调用差很多，要谨慎使用。", en:"We're using reflection here — it's significantly slower than a direct call, so use it carefully.", vocab:"reflection, performance, overhead"},
{zh:"这个类没有实现hashCode，放进HashMap会有问题。", en:"This class doesn't implement hashCode — it'll behave incorrectly in a HashMap.", vocab:"hashCode, HashMap"},
{zh:"这段代码的可读性不太好，我加了一些注释和命名更清晰的变量。", en:"This code wasn't very readable — I've added some comments and renamed the variables to make it clearer.", vocab:"readability, renamed, comments"},
{zh:"这里直接在controller里写了SQL，应该移到repository层。", en:"SQL is being written directly in the controller here — it should live in the repository layer.", vocab:"repository layer, separation of concerns"},
];
